### ISSUE TITLE
Question about form

### ISSUE THREAD

**Issue by isjaylee** [isjaylee/chatter#1]
@zznull For the input field at the bottom of the chat window, how would we make it follows Rails' convention? Or do we just leave it in straight HTML code?

I'm thinking it should be in form_for format. I tried doing "<%= form_for Message.new do | f | %>" but after submitting, it tries to find the create action.

https://github.com/isjaylee/chatter/blob/master/app/views/messages/index.html.erb#L32-L36

**Comment by zznull** [comment]
form_for is just a helper method. In this case it doesn't matter - all you need to do is get the value from input field and send it over a websocket connection. It's not like you have to worry about naming fields in post data or displaying error messages.

**Comment by isjaylee** [comment]
Ah, got it. Thanks.
